### ISSUE TITLE
Memory access exception in nn_conv2d_hstrip_tail_deep_padded

### ISSUE THREAD

**Issue by keithm-xmos** [xmos/lib_nn#3]
The following integration test configs cause a memory access exception in nn_conv2d_hstrip_tail_deep_padded.  

**NOTE: These tests pass when running on the x86 host.**  

```
integration_test/test_single_op_models/test_conv2d/test_conv2d.py::test_output[CONFIGS[4]]
integration_test/test_single_op_models/test_conv2d/test_conv2d.py::test_converted_single_op_model[CONFIGS[4]]
  4:
    K_h: 9
    K_w: 9
    height: 15
    input_channels: 32
    num_threads: 1
    output_channels: 4
    padding: same
    strides:
    - 2
    - 2
    width: 20
```

```
integration_test/test_single_op_models/test_conv2d/test_fused_relu/test_custom_relu_conv2d.py::test_output[CONFIGS[0]]
integration_test/test_single_op_models/test_conv2d/test_fused_relu/test_custom_relu_conv2d.py::test_idempotence[CONFIGS[0]]
  0:
    K_h: 2
    K_w: 3
    height: 5
    input_channels: 32
    max_value: 1.0
    num_threads: 1
    output_channels: 4
    padding: same
    strides:
    - 1
    - 2
    width: 20

```
