### ISSUE TITLE
Incorrect output from conv2d deep kernel function

### ISSUE THREAD

**Issue by keithm-xmos** [xmos/lib_nn#4]
The following integration test config produces incorrect output values for the 2nd output channel group.

**NOTE: This test passes when running on the x86 host.**

```
integration_test/test_single_op_models/test_conv2d/test_explicit_padding/test_padded_conv2d.py::test_output[CONFIGS[0]]
  0:
    K_h: 9
    K_w: 7
    height: 8
    input_channels: 32
    num_threads: 1
    output_channels: 28
    pad_b: 2
    pad_l: 1
    pad_r: 0
    pad_t: 0
    strides:
    - 2
    - 2
    width: 7
```

Predicted and expected output values:

```
idx=(0, 0, 16): diff=117, expected=10, predicted=127
idx=(0, 0, 17): diff=141, expected=-14, predicted=127
idx=(0, 0, 18): diff=-51, expected=58, predicted=7
idx=(0, 0, 19): diff=113, expected=14, predicted=127
idx=(0, 0, 20): diff=51, expected=76, predicted=127
idx=(0, 0, 21): diff=106, expected=21, predicted=127
idx=(0, 0, 22): diff=157, expected=-30, predicted=127
idx=(0, 0, 23): diff=62, expected=51, predicted=113
idx=(0, 0, 24): diff=-104, expected=115, predicted=11
idx=(0, 0, 25): diff=-199, expected=71, predicted=-128
idx=(0, 0, 26): diff=126, expected=1, predicted=127
idx=(0, 0, 27): diff=-141, expected=13, predicted=-128
```
